<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    name="ngw_terminal_status_faults"
    targetNamespace="http://www.aepona.com/wsdl/ngw/terminal_status/v1_0/faults"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:ngw_terminal_status_xsd="http://www.aepona.com/schema/ngw/terminal_status/v1_0">

  <wsdl:types>
    <xsd:schema elementFormDefault="qualified">
      <xsd:import namespace="http://www.aepona.com/schema/ngw/terminal_status/v1_0"
         schemaLocation="ngw_terminal_status_types_1_0.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="TerminalStatusException">
    <wsdl:part name="TerminalStatusException" element="ngw_terminal_status_xsd:TerminalStatusException"/>
  </wsdl:message>

</wsdl:definitions>
